obj-m := vbox3.o
CFLAGS_vbox3.o := -fno-stack-protector

all:
	$(CC) query_app.c -o query_app
	$(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
	${RM} query_app
